// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2ChatCbi
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ChatCbiResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifies the conversation. If chatID was provided in the request, this will be the same.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChatID { get; set; }
#nullable restore
#else
        public string ChatID { get; set; }
#endif
        /// <summary>ChatCbi response to the message. Example is an excerpt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>List of related references.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2ChatCbi.Result>? RelatedContent { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2ChatCbi.Result> RelatedContent { get; set; }
#endif
        /// <summary>List of sources used to generate the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2ChatCbi.Source>? Sources { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2ChatCbi.Source> Sources { get; set; }
#endif
        /// <summary>List of suggested follow-up questions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Suggestions { get; set; }
#nullable restore
#else
        public List<string> Suggestions { get; set; }
#endif
        /// <summary>Title of the chat</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse"/> and sets the default values.
        /// </summary>
        public ChatCbiResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "chatID", n => { ChatID = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "relatedContent", n => { RelatedContent = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2ChatCbi.Result>(global::TearLogic.Clients.Models.V2ChatCbi.Result.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sources", n => { Sources = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2ChatCbi.Source>(global::TearLogic.Clients.Models.V2ChatCbi.Source.CreateFromDiscriminatorValue)?.AsList(); } },
                { "suggestions", n => { Suggestions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("chatID", ChatID);
            writer.WriteStringValue("message", Message);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2ChatCbi.Result>("relatedContent", RelatedContent);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2ChatCbi.Source>("sources", Sources);
            writer.WriteCollectionOfPrimitiveValues<string>("suggestions", Suggestions);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
