// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using TearLogic.Clients.V2.Authorize;
using TearLogic.Clients.V2.Businessrelationships;
using TearLogic.Clients.V2.Chatcbi;
using TearLogic.Clients.V2.Chatcbichunked;
using TearLogic.Clients.V2.Financialtransactions;
using TearLogic.Clients.V2.Firmographics;
using TearLogic.Clients.V2.Managementandboard;
using TearLogic.Clients.V2.Organizations;
using TearLogic.Clients.V2.Outlook;
namespace TearLogic.Clients.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::TearLogic.Clients.V2.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::TearLogic.Clients.V2.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The businessrelationships property</summary>
        public global::TearLogic.Clients.V2.Businessrelationships.BusinessrelationshipsRequestBuilder Businessrelationships
        {
            get => new global::TearLogic.Clients.V2.Businessrelationships.BusinessrelationshipsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chatcbi property</summary>
        public global::TearLogic.Clients.V2.Chatcbi.ChatcbiRequestBuilder Chatcbi
        {
            get => new global::TearLogic.Clients.V2.Chatcbi.ChatcbiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chatcbichunked property</summary>
        public global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder Chatcbichunked
        {
            get => new global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The financialtransactions property</summary>
        public global::TearLogic.Clients.V2.Financialtransactions.FinancialtransactionsRequestBuilder Financialtransactions
        {
            get => new global::TearLogic.Clients.V2.Financialtransactions.FinancialtransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The firmographics property</summary>
        public global::TearLogic.Clients.V2.Firmographics.FirmographicsRequestBuilder Firmographics
        {
            get => new global::TearLogic.Clients.V2.Firmographics.FirmographicsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The managementandboard property</summary>
        public global::TearLogic.Clients.V2.Managementandboard.ManagementandboardRequestBuilder Managementandboard
        {
            get => new global::TearLogic.Clients.V2.Managementandboard.ManagementandboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::TearLogic.Clients.V2.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::TearLogic.Clients.V2.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The outlook property</summary>
        public global::TearLogic.Clients.V2.Outlook.OutlookRequestBuilder Outlook
        {
            get => new global::TearLogic.Clients.V2.Outlook.OutlookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
