// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2OrganizationLookup
{
    /// <summary>
    /// Search parameters to lookup a list of organization profiles. You must pass at least one search parameter.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OrgLookupRequestBody : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum number of organizations to be returned in a single response. Must be in the range [1, 100]. Defaults to 10.</summary>
        public int? Limit { get; set; }
        /// <summary>Names to look up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Names { get; set; }
#nullable restore
#else
        public List<string> Names { get; set; }
#endif
        /// <summary>Token to fetch the next page of results; provided in a previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPageToken { get; set; }
#nullable restore
#else
        public string NextPageToken { get; set; }
#endif
        /// <summary>Returns the corresponding organization profile. Note: This is mutually exclusive with the names and urls fields; an error will be returned if there are values for profileUrl and names or urls.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileUrl { get; set; }
#nullable restore
#else
        public string ProfileUrl { get; set; }
#endif
        /// <summary>The order in which the results will be returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody_sort? Sort { get; set; }
#nullable restore
#else
        public global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody_sort Sort { get; set; }
#endif
        /// <summary>URLs to look up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Urls { get; set; }
#nullable restore
#else
        public List<string> Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody"/> and sets the default values.
        /// </summary>
        public OrgLookupRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "names", n => { Names = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "nextPageToken", n => { NextPageToken = n.GetStringValue(); } },
                { "profileUrl", n => { ProfileUrl = n.GetStringValue(); } },
                { "sort", n => { Sort = n.GetObjectValue<global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody_sort>(global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody_sort.CreateFromDiscriminatorValue); } },
                { "urls", n => { Urls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("limit", Limit);
            writer.WriteCollectionOfPrimitiveValues<string>("names", Names);
            writer.WriteStringValue("nextPageToken", NextPageToken);
            writer.WriteStringValue("profileUrl", ProfileUrl);
            writer.WriteObjectValue<global::TearLogic.Clients.Models.V2OrganizationLookup.OrgLookupRequestBody_sort>("sort", Sort);
            writer.WriteCollectionOfPrimitiveValues<string>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
