// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2FinancialTransactions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FundingsOrg : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Capitalization table history. Lists the funded organization&apos;s ownership structure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.CapTable>? CapTableHistory { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.CapTable> CapTableHistory { get; set; }
#endif
        /// <summary>List of financial transactions where the organization received funding.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.Transaction>? Fundings { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.Transaction> Fundings { get; set; }
#endif
        /// <summary>CB Insights Organization ID.</summary>
        public int? OrgId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2FinancialTransactions.FundingsOrg"/> and sets the default values.
        /// </summary>
        public FundingsOrg()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2FinancialTransactions.FundingsOrg"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2FinancialTransactions.FundingsOrg CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2FinancialTransactions.FundingsOrg();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capTableHistory", n => { CapTableHistory = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.CapTable>(global::TearLogic.Clients.Models.V2FinancialTransactions.CapTable.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fundings", n => { Fundings = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.Transaction>(global::TearLogic.Clients.Models.V2FinancialTransactions.Transaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "orgId", n => { OrgId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.CapTable>("capTableHistory", CapTableHistory);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.Transaction>("fundings", Fundings);
            writer.WriteIntValue("orgId", OrgId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
