// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2FinancialTransactions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InvestmentsMultipleResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Token to fetch the next page of results. If the value is null, then there are no more results to page through.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPageToken { get; set; }
#nullable restore
#else
        public string NextPageToken { get; set; }
#endif
        /// <summary>A list of investments the requested Org ID participated in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsOrg>? Orgs { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsOrg> Orgs { get; set; }
#endif
        /// <summary>Total number of organizations with Portfolio Exits.</summary>
        public int? TotalHits { get; set; }
        /// <summary>Indicates whether totalHits is equal to (&apos;eq&apos;), or greater than or equal to (&apos;gte&apos;) the number of organizations with Portfolio Exits which can be fetched. Will be set to &apos;gte&apos; in the rare case where totalHits exceeds 10,000.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalHitsRelation { get; set; }
#nullable restore
#else
        public string TotalHitsRelation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsMultipleResponse"/> and sets the default values.
        /// </summary>
        public InvestmentsMultipleResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsMultipleResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsMultipleResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsMultipleResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "nextPageToken", n => { NextPageToken = n.GetStringValue(); } },
                { "orgs", n => { Orgs = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsOrg>(global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsOrg.CreateFromDiscriminatorValue)?.AsList(); } },
                { "totalHits", n => { TotalHits = n.GetIntValue(); } },
                { "totalHitsRelation", n => { TotalHitsRelation = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("nextPageToken", NextPageToken);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2FinancialTransactions.InvestmentsOrg>("orgs", Orgs);
            writer.WriteIntValue("totalHits", TotalHits);
            writer.WriteStringValue("totalHitsRelation", TotalHitsRelation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
