// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2BusinessRelationships
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MultipleOrganizationBusinessRelationshipsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Token to fetch the next page of results. If the value is null, then there are no more results to page through.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextPageToken { get; set; }
#nullable restore
#else
        public string NextPageToken { get; set; }
#endif
        /// <summary>A list of organizations with their business relationship details included.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2BusinessRelationships.OrganizationBusinessRelationshipsResponse>? Orgs { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2BusinessRelationships.OrganizationBusinessRelationshipsResponse> Orgs { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2BusinessRelationships.MultipleOrganizationBusinessRelationshipsResponse"/> and sets the default values.
        /// </summary>
        public MultipleOrganizationBusinessRelationshipsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2BusinessRelationships.MultipleOrganizationBusinessRelationshipsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2BusinessRelationships.MultipleOrganizationBusinessRelationshipsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2BusinessRelationships.MultipleOrganizationBusinessRelationshipsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "nextPageToken", n => { NextPageToken = n.GetStringValue(); } },
                { "orgs", n => { Orgs = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2BusinessRelationships.OrganizationBusinessRelationshipsResponse>(global::TearLogic.Clients.Models.V2BusinessRelationships.OrganizationBusinessRelationshipsResponse.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("nextPageToken", NextPageToken);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2BusinessRelationships.OrganizationBusinessRelationshipsResponse>("orgs", Orgs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
