// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Fundings;
using TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Investments;
using TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Portfolioexits;
namespace TearLogic.Clients.V2.Organizations.Item.Financialtransactions
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\organizations\{orgId}\financialtransactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FinancialtransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fundings property</summary>
        public global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Fundings.FundingsRequestBuilder Fundings
        {
            get => new global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Fundings.FundingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The investments property</summary>
        public global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Investments.InvestmentsRequestBuilder Investments
        {
            get => new global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Investments.InvestmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The portfolioexits property</summary>
        public global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Portfolioexits.PortfolioexitsRequestBuilder Portfolioexits
        {
            get => new global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.Portfolioexits.PortfolioexitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.FinancialtransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinancialtransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/organizations/{orgId}/financialtransactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Organizations.Item.Financialtransactions.FinancialtransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinancialtransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/organizations/{orgId}/financialtransactions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
