// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using TearLogic.Clients.Models.Common;
using TearLogic.Clients.Models.V2ChatCbi;
namespace TearLogic.Clients.V2.Chatcbichunked
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\chatcbichunked
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatcbichunkedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatcbichunkedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/chatcbichunked", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatcbichunkedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/chatcbichunked", rawUrl)
        {
        }
        /// <summary>
        /// Response is a series of incremental chunks. See https://api-docs.cbinsights.com/portal/docs/CBI-API/ChatCBI for more information and usage details. This endpoint uses generative AI and may make mistakes. Always verify pertinent information.
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 400 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 403 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 424 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse?> PostAsync(global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse> PostAsync(global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "403", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "424", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "500", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse>(requestInfo, global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Response is a series of incremental chunks. See https://api-docs.cbinsights.com/portal/docs/CBI-API/ChatCBI for more information and usage details. This endpoint uses generative AI and may make mistakes. Always verify pertinent information.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::TearLogic.Clients.Models.V2ChatCbi.ChatCbiRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder WithUrl(string rawUrl)
        {
            return new global::TearLogic.Clients.V2.Chatcbichunked.ChatcbichunkedRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChatcbichunkedRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
