// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using TearLogic.Clients.Models.Common;
using TearLogic.Clients.Models.V2BusinessRelationships;
namespace TearLogic.Clients.V2.Organizations.Item.Businessrelationships
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\organizations\{orgId}\businessrelationships
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BusinessrelationshipsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Organizations.Item.Businessrelationships.BusinessrelationshipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessrelationshipsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/organizations/{orgId}/businessrelationships", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.V2.Organizations.Item.Businessrelationships.BusinessrelationshipsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BusinessrelationshipsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/organizations/{orgId}/businessrelationships", rawUrl)
        {
        }
        /// <summary>
        /// Retrieved data includes partnerships, client/vendor relationships, and licensing activity, plus AI-generated insights to predict future M&amp;As and shifts in strategy.
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2BusinessRelationships.BusinessRelationshipsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 400 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 403 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 424 status code</exception>
        /// <exception cref="global::TearLogic.Clients.Models.Common.ErrorWithCode">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::TearLogic.Clients.Models.V2BusinessRelationships.BusinessRelationshipsResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::TearLogic.Clients.Models.V2BusinessRelationships.BusinessRelationshipsResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "403", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "424", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
                { "500", global::TearLogic.Clients.Models.Common.ErrorWithCode.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::TearLogic.Clients.Models.V2BusinessRelationships.BusinessRelationshipsResponse>(requestInfo, global::TearLogic.Clients.Models.V2BusinessRelationships.BusinessRelationshipsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieved data includes partnerships, client/vendor relationships, and licensing activity, plus AI-generated insights to predict future M&amp;As and shifts in strategy.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.V2.Organizations.Item.Businessrelationships.BusinessrelationshipsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::TearLogic.Clients.V2.Organizations.Item.Businessrelationships.BusinessrelationshipsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::TearLogic.Clients.V2.Organizations.Item.Businessrelationships.BusinessrelationshipsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BusinessrelationshipsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
