// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2Outlook
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommercialMaturity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Signals that are affecting the commercial maturity of the company.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::TearLogic.Clients.Models.V2Outlook.CommercialMaturitySignals? CommercialMaturitySignals { get; set; }
#nullable restore
#else
        public global::TearLogic.Clients.Models.V2Outlook.CommercialMaturitySignals CommercialMaturitySignals { get; set; }
#endif
        /// <summary>The maturity level of the company.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::TearLogic.Clients.Models.V2Outlook.MaturityLevel? MaturityLevel { get; set; }
#nullable restore
#else
        public global::TearLogic.Clients.Models.V2Outlook.MaturityLevel MaturityLevel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2Outlook.CommercialMaturity"/> and sets the default values.
        /// </summary>
        public CommercialMaturity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2Outlook.CommercialMaturity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2Outlook.CommercialMaturity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2Outlook.CommercialMaturity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commercialMaturitySignals", n => { CommercialMaturitySignals = n.GetObjectValue<global::TearLogic.Clients.Models.V2Outlook.CommercialMaturitySignals>(global::TearLogic.Clients.Models.V2Outlook.CommercialMaturitySignals.CreateFromDiscriminatorValue); } },
                { "maturityLevel", n => { MaturityLevel = n.GetObjectValue<global::TearLogic.Clients.Models.V2Outlook.MaturityLevel>(global::TearLogic.Clients.Models.V2Outlook.MaturityLevel.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::TearLogic.Clients.Models.V2Outlook.CommercialMaturitySignals>("commercialMaturitySignals", CommercialMaturitySignals);
            writer.WriteObjectValue<global::TearLogic.Clients.Models.V2Outlook.MaturityLevel>("maturityLevel", MaturityLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
