// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2Outlook
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExitProbabilityHistoryResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ipo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>? Ipo { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore> Ipo { get; set; }
#endif
        /// <summary>The mna property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>? Mna { get; set; }
#nullable restore
#else
        public List<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore> Mna { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityHistoryResponse"/> and sets the default values.
        /// </summary>
        public ExitProbabilityHistoryResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityHistoryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityHistoryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityHistoryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ipo", n => { Ipo = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>(global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mna", n => { Mna = n.GetCollectionOfObjectValues<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>(global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>("ipo", Ipo);
            writer.WriteCollectionOfObjectValues<global::TearLogic.Clients.Models.V2Outlook.HistoricalExitProbabilityScore>("mna", Mna);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
