// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2Outlook
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExitProbabilityScore : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Date at which the exit probability was calculated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AsOfDate { get; set; }
#nullable restore
#else
        public string AsOfDate { get; set; }
#endif
        /// <summary>The exit probability of the company within the next 2 years.</summary>
        public double? ExitProbability { get; set; }
        /// <summary>The mean exit probability of similar companies.</summary>
        public double? MeanProbability { get; set; }
        /// <summary>The exit probability of the company as compared to similar companies.</summary>
        public double? RatioToMean { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityScore"/> and sets the default values.
        /// </summary>
        public ExitProbabilityScore()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityScore"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityScore CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2Outlook.ExitProbabilityScore();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asOfDate", n => { AsOfDate = n.GetStringValue(); } },
                { "exitProbability", n => { ExitProbability = n.GetDoubleValue(); } },
                { "meanProbability", n => { MeanProbability = n.GetDoubleValue(); } },
                { "ratioToMean", n => { RatioToMean = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("asOfDate", AsOfDate);
            writer.WriteDoubleValue("exitProbability", ExitProbability);
            writer.WriteDoubleValue("meanProbability", MeanProbability);
            writer.WriteDoubleValue("ratioToMean", RatioToMean);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
