// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2Outlook
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScoreInsights : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The negativeTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? NegativeTags { get; set; }
#nullable restore
#else
        public List<string> NegativeTags { get; set; }
#endif
        /// <summary>The percentile property</summary>
        public double? Percentile { get; set; }
        /// <summary>The pointChange property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::TearLogic.Clients.Models.V2Outlook.PointChange? PointChange { get; set; }
#nullable restore
#else
        public global::TearLogic.Clients.Models.V2Outlook.PointChange PointChange { get; set; }
#endif
        /// <summary>The positiveTags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PositiveTags { get; set; }
#nullable restore
#else
        public List<string> PositiveTags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2Outlook.ScoreInsights"/> and sets the default values.
        /// </summary>
        public ScoreInsights()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2Outlook.ScoreInsights"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2Outlook.ScoreInsights CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2Outlook.ScoreInsights();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "negativeTags", n => { NegativeTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "percentile", n => { Percentile = n.GetDoubleValue(); } },
                { "pointChange", n => { PointChange = n.GetObjectValue<global::TearLogic.Clients.Models.V2Outlook.PointChange>(global::TearLogic.Clients.Models.V2Outlook.PointChange.CreateFromDiscriminatorValue); } },
                { "positiveTags", n => { PositiveTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("negativeTags", NegativeTags);
            writer.WriteDoubleValue("percentile", Percentile);
            writer.WriteObjectValue<global::TearLogic.Clients.Models.V2Outlook.PointChange>("pointChange", PointChange);
            writer.WriteCollectionOfPrimitiveValues<string>("positiveTags", PositiveTags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
