// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace TearLogic.Clients.Models.V2ScoutingReports
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScoutingReportResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Basic information &amp; CB Insights proprietary metrics regarding the organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::TearLogic.Clients.Models.V2ScoutingReports.OrgInfo? OrgInfo { get; set; }
#nullable restore
#else
        public global::TearLogic.Clients.Models.V2ScoutingReports.OrgInfo OrgInfo { get; set; }
#endif
        /// <summary>Scouting Report for the organization in JSON format. Please note that citation links are currently not included in the JSON version. Example is an excerpt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReportJson { get; set; }
#nullable restore
#else
        public string ReportJson { get; set; }
#endif
        /// <summary>Scouting Report for the organization in Markdown format (after parsing the JSON string). Includes citations. Example is an excerpt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReportMarkdown { get; set; }
#nullable restore
#else
        public string ReportMarkdown { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::TearLogic.Clients.Models.V2ScoutingReports.ScoutingReportResponse"/> and sets the default values.
        /// </summary>
        public ScoutingReportResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::TearLogic.Clients.Models.V2ScoutingReports.ScoutingReportResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::TearLogic.Clients.Models.V2ScoutingReports.ScoutingReportResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::TearLogic.Clients.Models.V2ScoutingReports.ScoutingReportResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "orgInfo", n => { OrgInfo = n.GetObjectValue<global::TearLogic.Clients.Models.V2ScoutingReports.OrgInfo>(global::TearLogic.Clients.Models.V2ScoutingReports.OrgInfo.CreateFromDiscriminatorValue); } },
                { "reportJson", n => { ReportJson = n.GetStringValue(); } },
                { "reportMarkdown", n => { ReportMarkdown = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::TearLogic.Clients.Models.V2ScoutingReports.OrgInfo>("orgInfo", OrgInfo);
            writer.WriteStringValue("reportJson", ReportJson);
            writer.WriteStringValue("reportMarkdown", ReportMarkdown);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
